# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('estado', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(default='pendiente', max_length=200)),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_comprada', models.IntegerField()),
                ('estado', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAbandonarVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ViviendaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='activo', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='YearMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yearmonth',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AddField(
            model_name='solicitudabandonarvivienda',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Vivienda'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='year_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.YearMonth'),
        ),
        migrations.AddField(
            model_name='listacompras',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='itemlista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ListaCompras'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='invitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='lista_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ListaCompras'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='year_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.YearMonth'),
        ),
        migrations.AlterUniqueTogether(
            name='viviendausuario',
            unique_together=set([('vivienda', 'user', 'fecha_creacion')]),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=set([('categoria', 'vivienda', 'year_month')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemlista',
            unique_together=set([('item', 'lista')]),
        ),
    ]
