# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import expenses_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(default='pendiente', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_medida', models.CharField(default='unidad', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_comprada', models.IntegerField(blank=True, default=0, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAbandonarVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ViviendaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Categoria')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='ViviendaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='activo', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_abandono', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yearmonth',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AddField(
            model_name='viviendausuario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viviendausuario',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Vivienda'),
        ),
        migrations.AddField(
            model_name='solicitudabandonarvivienda',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.Vivienda'),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='year_month',
            field=models.ForeignKey(default=expenses_manager.models.get_current_yearMonth, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.YearMonth'),
        ),
        migrations.AddField(
            model_name='listacompras',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='itemlista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ListaCompras'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='invitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creado_por', to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.ForeignKey(blank=True, default=expenses_manager.models.get_default_estadoGasto, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.EstadoGasto'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='lista_compras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ListaCompras'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.ViviendaUsuario'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='year_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses_manager.YearMonth'),
        ),
        migrations.AlterUniqueTogether(
            name='viviendausuario',
            unique_together=set([('vivienda', 'user', 'estado', 'fecha_creacion')]),
        ),
        migrations.AlterUniqueTogether(
            name='presupuesto',
            unique_together=set([('categoria', 'vivienda', 'year_month')]),
        ),
        migrations.AlterUniqueTogether(
            name='itemlista',
            unique_together=set([('item', 'lista')]),
        ),
    ]
