language: python

python:
  - "3.5.2"

services: postgresql

addons:
  postgresql: "9.5"

install:
  - sudo apt-get update
  - sudo apt-get install -y python3-dev libjpeg-dev
  - pip install --upgrade pip
  - pip install -r requirements/dev.txt
  - pip install coveralls

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp paguen_po/config/secrets.json.travisCI paguen_po/config/secrets.json
  - python paguen_po/manage.py makemigrations users vacations periods households groceries expenses categories budgets

  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn

script:
  - pep8 paguen_po --max-line-length=119 --exclude="*/migrations/*","*wsgi.py"
  - travis-sphinx build
  - cd paguen_po
  - python manage.py migrate
  - coverage run --source='.' --omit='*/migrations/*','config/settings/*','*__init__.py*','*apps.py','config/wsgi.py','manage.py' manage.py test -k
  - coverage report

after_success:
  - travis-sphinx deploy
  - coveralls
  - cd ..
  - requires.io update-branch -t $REQUIRES_IO_TOKEN -r paguenpo -n master requirements/*.txt

notifications:
  email: false
