language: python

python:
  - "3.5"

services: postgresql

postgresql:
  - "9.5.5"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq python3-pip python3-dev libjpeg-dev
  - pip install --upgrade pip
  - pip install -r requirements/dev.txt

before_script:
  - cp paguen_po/config/secrets.json.travisCI paguen_po/config/secrets.json

script:
  - ls
  - python paguen_po/manage.py makemigrations
