version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "cp paguen_po/config/secrets.json.docker paguen_po/config/secrets.json && make build && make run"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db