# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('PENDING', 'pendiente'), ('PAID', 'pagado')], default='PENDING', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('amount', models.PositiveIntegerField(verbose_name='monto')),
                ('year', models.PositiveIntegerField(verbose_name='año')),
                ('month', models.PositiveIntegerField(verbose_name='mes')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Category')),
                ('roommate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.Roommate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
