# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_auto_20170813_1841'),
        ('expenses', '0003_auto_20170813_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='households.Household'),
        ),
    ]
